/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMethod */

#ifndef _Included_NativeMethod
#define _Included_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMethod
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMethod_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
